### PR TITLE
Revert "[Rakefile] Run specs in release task with only released dependen...

### PR DESCRIPTION
**Pull request by segiddins**
Reverts CocoaPods/Rainforest#37

### CODE REVIEW

**Comment by alloy** [comment]
Why?

**Comment by segiddins** [comment]
It had unintended consequences. 

-Samuel E. Giddins

On Apr 30, 2015, at 1:09 AM, Eloy Durán <notifications@github.com> wrote:

Why?

**Comment by alloy** [comment]
…such as?

**Comment by segiddins** [comment]
It always using the latest version of rubocop, making Kyle and I avoid this entire code path when doing the past few releases. 

-Samuel E. Giddins

On Apr 30, 2015, at 4:08 AM, Eloy Durán <notifications@github.com> wrote:

…such as?

**Comment by alloy** [comment]
Aha, yeah that sounds annoying.

And so you don’t feel the need anymore to have this safety net since that bodged release? :)

**Comment by segiddins** [comment]
Anything that makes me disable checks is a hinderence rather that a help. 

-Samuel E. Giddins

On Apr 30, 2015, at 4:16 AM, Eloy Durán <notifications@github.com> wrote:

Aha, yeah that sounds annoying.

And so you don’t feel the need anymore to have this safety net since that bodged release? :)

**Comment by mrackwitz** [comment]
What about parsing the Gemfile/Lockfile and reduce it to the subset of dependencies, which are in the `spec` group, so that rubocop et al. will keep locked? Too much effort for too little in return?

**Pull request merged**
