### PR TITLE
[Rakefile] Add cocoapods-acknowledgements to list of gems

### PR DESCRIPTION
**Pull request by segiddins**
\c @orta

### CODE REVIEW

**Comment by orta** [comment]
Yep, looks good to go on :green_apple:

**Comment by orta** [comment]
screen shot 2016-03-07 at 12 10 34 pm

interesting fail, will retry

**Comment by segiddins** [comment]
Travis and this repo don't play along, don't worry about the fail ;)

**Comment by orta** [comment]
:+1:

**Pull request merged**
