### PR TITLE
make it clear that this repo requires updating and shouldn't be used

### PR DESCRIPTION
**Pull request by prohoney**
While I'm very happy with the days spent learning ruby, rake, rbenv, bundler and how to fix environmental issues. I think being loud and clear that the repo needs an update can save future dev time. 

@dnkoutso's [comment](https://github.com/CocoaPods/Rainforest/issues/89#issuecomment-752263648) on the issue I opened:

> that probably needs updating to be honest.

### CODE REVIEW

**Review by paulb777 — APPROVED** [review]
LGTM! I did similar spinning when I first tried to contribute to CocoaPods.

It would also be great to remove the Rainforest references from https://guides.cocoapods.org/contributing/dev-environment.html. I'll make a PR for that.

**Comment by prohoney** [comment]
@paulb777 Great idea. I wasn't so sure what exactly to put there instead of a simple clone and bootstrap. Thank you!

**Comment by paulb777** [comment]
https://github.com/CocoaPods/guides.cocoapods.org/pull/196

**Comment by prohoney** [comment]
@paulb777 Do you know what else needs to be done so this can get merged?

**Comment by paulb777** [comment]
@dnkoutso Can you help here?

**Comment by dnkoutso** [comment]
Merged. CI has been broken for a while here. We can fix but not yet.

**Comment by prohoney** [comment]
@dnkoutso 🎉 🎉 🎉  Tiny but first OSS contribution

**Comment by paulb777** [comment]
Congrats @prohoney ! 🎉 🎉 🎉

**Pull request merged**
