### PR TITLE
Super release

### PR DESCRIPTION
**Pull request by segiddins**
Add a super-release task. This is what I've been using to do release for ~1 month.

### CODE REVIEW

**Comment by segiddins** [comment]
(This is also what I used to release CocoaPods 1.0)

**Comment by neonichu** [comment]
😍

**Comment by alloy** [comment]
Yay, sweet automation! 👍

**Comment by segiddins** [comment]
When I have a few spare hours, I'm going to re-organize this rakefile to be a bit less of a monolith. When I do that, I'm going to merge

**Comment by segiddins** [comment]
I don't have the energy to refactor this right now, so I'd like to merge it as-is

**Comment by neonichu** [comment]
Seems 👌 to me

**Comment by segiddins** [comment]
:ship:

**Pull request merged**
